// Code generated by gen-adapters. DO NOT EDIT.

package pi

import "github.com/archhaeondlg/aiusage/internal/adapter/shared"

type PiAdapter struct{ *shared.GenericAdapter }

func NewAdapter() *PiAdapter {
	return &PiAdapter{shared.NewGenericAdapter("pi", []string{
		"~/.pi-agent",
		"~/.config/pi-agent",
	})}
}
