// Code generated by gen-adapters. DO NOT EDIT.

package copilot

import "github.com/archhaeondlg/aiusage/internal/adapter/shared"

type CopilotAdapter struct{ *shared.GenericAdapter }

func NewAdapter() *CopilotAdapter {
	return &CopilotAdapter{shared.NewGenericAdapter("copilot", []string{
		"~/.github-copilot",
		"~/.config/github-copilot",
	})}
}
