package main

import (
	"fmt"
	"os"
	"strings"
)

type thinAdapter struct {
	Name  string
	Paths []string
}

var thinAdapters = []thinAdapter{
	{"qwen", []string{"~/.qwen", "~/.config/qwen"}},
	{"pi", []string{"~/.pi-agent", "~/.config/pi-agent"}},
	{"openclaw", []string{"~/.openclaw", "~/.config/openclaw"}},
	{"copilot", []string{"~/.github-copilot", "~/.config/github-copilot"}},
	{"kimi", []string{"~/.kimi", "~/.config/kimi"}},
	{"kilo", []string{"~/.kilo", "~/.config/kilo"}},
	{"hermes", []string{"~/.hermes", "~/.config/hermes"}},
	{"goose", []string{"~/.goose", "~/.config/goose"}},
	{"codebuff", []string{"~/.codebuff"}},
	{"gemini", []string{"~/.gemini", "~/.config/gemini", "~/.config/google-gemini"}},
	{"amp", []string{"~/.amp", "~/.config/amp"}},
	{"droid", []string{"~/.droid", "~/.config/droid"}},
}

func typeName(name string) string {
	return strings.ToUpper(name[:1]) + name[1:] + "Adapter"
}

func genMod(a thinAdapter) string {
	pkg := a.Name
	typ := typeName(a.Name)

	var paths []string
	for _, p := range a.Paths {
		paths = append(paths, fmt.Sprintf("\t\t%q,", p))
	}
	pathBlock := strings.Join(paths, "\n")

	return fmt.Sprintf(`// Code generated by gen-adapters. DO NOT EDIT.

package %s

import "github.com/archhaeondlg/aiusage/internal/adapter/shared"

type %s struct{ *shared.GenericAdapter }

func NewAdapter() *%s {
	return &%s{shared.NewGenericAdapter(%q, []string{
%s
	})}
}
`, pkg, typ, typ, typ, a.Name, pathBlock)
}

func main() {
	for _, a := range thinAdapters {
		dir := fmt.Sprintf("internal/adapter/%s", a.Name)
		if err := os.MkdirAll(dir, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "mkdir %s: %v\n", dir, err)
			os.Exit(1)
		}
		path := fmt.Sprintf("%s/mod.go", dir)
		content := genMod(a)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
			os.Exit(1)
		}
		fmt.Printf("generated %s\n", path)
	}
}
