// Code generated by gen-adapters. DO NOT EDIT.

package amp

import "github.com/archhaeondlg/aiusage/internal/adapter/shared"

type AmpAdapter struct{ *shared.GenericAdapter }

func NewAdapter() *AmpAdapter {
	return &AmpAdapter{shared.NewGenericAdapter("amp", []string{
		"~/.amp",
		"~/.config/amp",
	})}
}
