// Code generated by gen-adapters. DO NOT EDIT.

package goose

import "github.com/archhaeondlg/aiusage/internal/adapter/shared"

type GooseAdapter struct{ *shared.GenericAdapter }

func NewAdapter() *GooseAdapter {
	return &GooseAdapter{shared.NewGenericAdapter("goose", []string{
		"~/.goose",
		"~/.config/goose",
	})}
}
